package com.example.socialnetworking.controller;

import com.example.socialnetworking.moldel.Post;

import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/post")
public class PostController {

    @RequestMapping(value = "/publish",method = RequestMethod.POST)
    public void publishPost(@RequestBody Post post){

        /*
            This method is generated to receive the message from the UI and pass it to the service to save it into the database.
            @param 
                Post: Object -> id:      is null; as it will be generated by the model
                                message: String
        */

        

    }

}
